### ISSUE TITLE
Update linters.yaml to run linters on PR and push to main

### ISSUE THREAD

**Issue by michaeljwood** [cfpb/regtech-api-commons#184]
Need to update the linters.yaml with the following:

```
on:
  pull_request:
  push:
    branches:
      - "main"
```
